jwt:
  key: ${JWT_KEY}
  expire: ${JWT_EXPIRE}

spring:
  application:
    name: test_spring

  datasource:
    driver-class-name: ${DB_SERVER}
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

